export default {
  GET_REPOS_BY_REPO_REQUEST: "GET_REPOS_BY_REPO_REQUEST",
  GET_REPOS_BY_REPO_SUCCESS: "GET_REPOS_BY_REPO_SUCCESS",
  GET_REPOS_BY_REPO_FAILED: "GET_REPOS_BY_REPO_FAILED",

  ADD_REPOSITORY: "ADD_REPOSITORY",
};
